name: betterSleeping
author: vallas, and MetamorphicMike
version: 1.3
main: be.dezijwegel.bettersleeping.BetterSleeping
description: A plugin that makes sleeping in multiplayer fun again!
commands:
    bettersleeping:
        description: Reload the configuration files of BetterSleeping
        usage: /bettersleeping reload
        permission: bettersleeping.reload